// This file is "model.dart"
import 'package:app/domain/enums/user_role.dart';
import 'package:dart_mappable/dart_mappable.dart';
import 'package:mock_data/mock_data.dart';

// Will be generated by dart_mappable
part 'user.mapper.dart';

@MappableClass(
  caseStyle: CaseStyle.snakeCase,
)
class User with UserMappable {
  final String id;
  final String name;

  final String username;
  final String email;
  final String? imageUrl;
  final UserRole role;

  User({
    required this.id,
    required this.name,
    required this.username,
    required this.email,
    this.imageUrl,
    required this.role,
  });

  User.mock()
      : this(
          id: mockUUID(),
          name: mockName(),
          username: mockName().toLowerCase().replaceAll(' ', ''),
          email: '${mockName().toLowerCase().replaceAll(' ', '')}@example.com',
          role: UserRole.regular,
        );

  User.guest()
      : this(
          id: mockUUID(),
          name: 'Guest',
          username: 'guest',
          email: 'guest@example.com',
          role: UserRole.regular,
        );
}
